config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'

  devise_for :users, skip: "registrations"
  devise_scope :user do
    get "users/sign_up", to: "devise/registrations#new", as: "new_user_registration"
    post "users/sign_up", to: "devise/registrations#create", as: "user_registration"
    get "users/account", to: "devise/registrations#edit", as: "edit_user_registration"
    put "users/update", to: "devise/registrations#update", as: "update_user_registration"
    delete "users/clean", to: "devise/registrations#destroy", as: "clean_up"

  end

  get "admin", to: "users#index", as: "admin"
  get "users/:id", to: "users#show", as: "user_profile"
  patch "users/:id/subscribe", to: "users#follow"
  patch "users/:id/unsubscribe", to: "users#unfollow"
  patch "users/:id/ban", to: "users#ban"
  patch "users/:id/warn", to: "users#warn"

  get "activities", to: "activities#log"
  get "admin/activities", to: "activities#index"
  get "admin/activities/:id", to: "activities#show"

  resources :notifications, only: [:log, :index, :show, :create, :destroy]

  resources :posts do
    member do
      patch 'like', to: "posts#like"
    end
    resources :comments
  end

  resources :messages

  resources :friendships, only: [:log, :index, :show, :create, :destroy]

  root "posts#front"

  mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  resourcify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :friendships, dependent: :destroy
  has_many :messages
  acts_as_followable
  acts_as_follower

  mount_uploader :image, ImageUploader

  include PublicActivity::Model
  tracked

  after_create :set_role

  private
  def set_role
    self.add_role(:newbie) if self.roles.blank?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :follow, :unfollow, :block, :ban]
  check_authorization


  def index
    authorize! :index, User
    @users = User.all
  end

  def show
    @posts = @user.posts.order("updated_at DESC")
    authorize! :show, @user
  end

  def follow
    authorize! :follow, @user
    current_user.follow(@user)
    redirect_back fallback_location: user_profile_path(@user)
    current_user.create_activity key: "user.follow", owner: current_user, recipient: @user
  end

  def unfollow
    authorize! :unfollow, @user
    current_user.stop_following(@user)
    redirect_back fallback_location: user_profile_path(@user)
    current_user.create_activity key: "user.unfollow", owner: current_user, recipient: @user
  end

  def block
    # unfinished
    @user.block(@user)
  end

  def ban
    authorize! :ban, @user
    @user.banned = true
    if @user.save
      flash[:notice] = "User #{@user.name} was banned."
      current_user.create_activity key: "user.ban", owner: current_user, recipient: @user
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :birthday, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<div class="panel-body" id="profile-body">
  <p>Name: <%= @user.name %></p>
  <p>Birthday: <%= @user.birthday %></p>
  <p>Email: <%= @user.email %></p>
</div>

<% if current_user == @user %>
  <div class="panel-footer" id="profile-footer">
    <div class="label label-success">
      Joined since <%= @user.created_at %>
    </div>
    <div class="label label-warning">
      <%= link_to "/activities" do %>
        Check my acctivities
      <% end %>
    </div>
  </div>
<% else %>
  <div class="panel-footer">

    <% @friendships = current_user.friendships.where(friend_id: @user) %>
    <% if @friendships.present? %>
      <% @friendship = @friendships.last %>
      <% if @friendship.confirmed? %>
        <div class="text-success">
          <i class="fa fa-child"> Hello My Friend</i>
        </div>
      <% end %>
    <% end %>

    <div class="btn-group">
      <% if @friendship.present? %>
        <% if @friendship.confirmed? %>
          <%= link_to friendship_path(@friendship), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-info" do %>
            <i class="fa fa-meh-o"> Unfriend</i>
          <% end %>
        <% else %>
          <div class="btn btn-info">
            <i class="fa fa-spinner"> Request Sent</i>
          </div>
        <% end %>
      <% else %>
        <%= link_to friendships_path(friend_id: @user), method: :post, class: "btn btn-info" do %>
          <i class="fa fa-smile-o"> Make Friend</i>
        <% end %>
      <% end %>

      <% if current_user.following?(@user) %>
        <%= link_to "/users/#{@user.id}/unsubscribe", method: :patch, class: "btn btn-info" do %>
          <i class="fa fa-eye">Unsubscribe</i>
        <% end %>
      <% else %>
        <%= link_to "/users/#{@user.id}/subscribe", method: :patch, class: "btn btn-info" do %>
          <i class="fa fa-eye">Subscribe</i>
        <% end %>
      <% end %>

    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render "layouts/notice-box" %>

<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default animated fadeIn" id="notice-box">
    <p id="notice"><i class="fa fa-wrench"> This page is still under construction</i></p>
  </div>
</div>

<div class="col-md-8 col-md-offset-2">

  <% @users.each do |user| %>
    <div class="panel panel-default animated fadeIn">

      <div class="panel-heading" id="manager-heading">
        <div class="nav">
          <div class="navbar-left">
            <%= image_tag user.image_url(:thumb), width: 20, height: 20, class: "img-circle", id: "manager-img" unless user.image_url.nil? %>&nbsp&nbsp
          </div>
          <div class="navbar-left" id="manager-name">
            <%=  link_to user_profile_path(user) do %>
              <p><%= user.name %></p>
            <% end %>
          </div>
        </div>
      </div>

      <div class="panel-body">
        <span class="label label-success">Personal Info</span>
        <div id="manager-body">
          <ul class="text-success list-group">
            <li><strong>Name:&nbsp</strong><%= user.name %></li>
            <li><strong>Email:&nbsp</strong><%= user.email %></li>
            <li><strong>Birthday:&nbsp</strong><%= user.birthday %></li>
            <li><strong>Description&nbsp</strong><%# user.description %></li>
            <li><strong>Friendship&nbsp</strong><%# user.description %></li>
          </ul>
        </div>

        <% if user.has_role?(:Zucker, user) %>
          <% role = "Zucker" %>
        <% elsif user.has_role?(:admin, user) %>
          <% role = "admin" %>
        <% elsif user.has_role?(:newbie, user) %>
          <% role = "newbie" %>
        <% else %>
          <% role = "unknown" %>
        <% end %>

        <span class="label label-primary">Status</span>
        <div id="manager-body">
          <ul class="text-primary list-group" id="manager-links" >
            <li>Role?&nbsp&nbsp<span id="links-label"><%= role %></span></li>
            <li>Can/Cannot?</li>
            <li><%= link_to "Recent Activity?", "/admin/activities/#{user.id}", id: "manager-link" %><span id="links-label"><i class="fa fa-angle-double-left">  check</i></span></li>
          </ul>
        </div>

        <span class="label label-default">Login File</span>
        <div id="manager-body">
          <ul class="text-default list-group">
            <li><strong>Login times?&nbsp</strong><%= user.sign_in_count %></li>
            <% if user_signed_in? %>
              <li><strong>Current login at?&nbsp</strong><%= user.current_sign_in_at %></li>
              <li><strong>Current login on?&nbsp</strong><%= user.current_sign_in_ip %></li>
            <% end %>
            <li><strong>Last login at?&nbsp</strong><%= user.last_sign_in_at %></li>
            <li><strong>Last login on?&nbsp</strong><%= user.last_sign_in_ip %></li>
            <li><strong>Created at?&nbsp</strong><%= user.created_at %></li>
            <li><strong>Updated at?&nbsp</strong><%= user.updated_at %></li>
          </ul>
        </div>
      </div>

      <div class="panel-footer" id="manager-footer">
        <div class="btn-group">

          <%# link_to "View Friendship", "#", class: "btn btn-info" %>

          <button type="button" class="btn btn-danger">
            <%= link_to "BAN", "/users/#{user.id}/ban", method: :patch %>
          </button>
          <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expaned="false">
            Send Warning
          </button>
          <ul class="dropdown-menu" id="warning-message">
              <div class="nav navbar-nav navbar-default">
                <div class="navbar-header">
                  <div class="navbar-brand">
                    <%= image_tag current_user.image_url(:thumb), width: 20, height: 20, class: "img-circle"  unless current_user.image_url.nil? %>
                  </div>
                </div>
                <%= form_with url: "/users/#{user.id}/warn", method: :patch, class: "navbar-form navbar-left" do |f| %>
                  <div class="form-group">
                    <%= f.text_field :content, placeholder: "Write down warning messages...", class: "form-control", required: true %>
                  </div>
                  <%= f.submit "Enter", class: "btn btn-default" %>
                <% end %>
              </div>
          </ul>


        </div>
      </div>

      <br>
      <br>

    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render "layouts/notice-box" %>

<div class="clear-fix">

  <div class="col-md-4" id="profile">
    <div class="panel panel-default animated fadeIn">

      <div class="panel-heading" id="profile-head">
        <div class="nav">
          <div class="navbar-left">
            <%= image_tag @user.image_url(:medium), width: 100, height: 100 unless @user.image_url.nil? %>&nbsp&nbsp
          </div>
        </div>
      </div>

      <%= render "profile" %>

    </div>
  </div>

  <div class="col-md-8">
    <%= render @posts || "posts/post"  %>
  </div>
</div>