config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'

  devise_for :users, skip: "registrations"
  devise_scope :user do
    get "users/sign_up", to: "devise/registrations#new", as: "new_user_registration"
    post "users/sign_up", to: "devise/registrations#create", as: "user_registration"
    get "users/account", to: "devise/registrations#edit", as: "edit_user_registration"
    put "users/update", to: "devise/registrations#update", as: "update_user_registration"
    delete "users/clean", to: "devise/registrations#destroy", as: "clean_up"

  end

  get "admin", to: "users#index", as: "admin"
  get "users/:id", to: "users#show", as: "user_profile"
  patch "users/:id/subscribe", to: "users#follow"
  patch "users/:id/unsubscribe", to: "users#unfollow"
  patch "users/:id/ban", to: "users#ban"
  patch "users/:id/warn", to: "users#warn"

  get "activities", to: "activities#log"
  get "admin/activities", to: "activities#index"
  get "admin/activities/:id", to: "activities#show"

  resources :notifications, only: [:log, :index, :show, :create, :destroy]

  resources :posts do
    member do
      patch 'like', to: "posts#like"
    end
    resources :comments
  end

  resources :messages

  resources :friendships, only: [:log, :index, :show, :create, :destroy]

  root "posts#front"

  mount ActionCable.server => "/cable"
end

app/models/post.rb
require 'elasticsearch/model'

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable
  resourcify

  include PublicActivity::Model
  tracked
  # tracked owner: Proc.new{ |controller, model| controller.current_user }

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

=begin
  searchable do
    text :body
    text :comments do
        comments.map { |comment| comment.content }
    end
    integer :user_id
    time :updated_at
    time :created_at
  end
=end

  # This function will be called by PostsController

=begin
  def self.search(query)
    __elasticsearch__.search(query) do
      #########  DSL  ###########
    end
  end
=end


end

Post.import(force: true)

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:front]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  check_authorization
  skip_authorization_check only: [:front]

  def front
    if user_signed_in?
      redirect_to posts_path
    else
      @posts = Post.includes(:user).where(public: true).order("updated_at DESC")
    end
  end

  def index
    authorize! :index, Post
=begin
    search = Post.search(include: [:user]) do
      fulltext params[:key]
      order_by(:updated_at, :desc)
      # by default sunspot will do pagination for us and :per_page = 30
      # paginate(page: 2, per_page: 15)
    end
    @posts = search.results

    # If do without sunspot:
    # @posts = Post.order("updated_at DESC").paginate(page: params[:page], per_page: 10)
=end
    if params[:key]
      @results = Post.search(params[:key])
      @posts = @results.records.includes(:user).order("updated_at DESC")
    else
      @posts = Post.includes(:user).order("updated_at DESC")
    end
  end

  def show
    authorize! :show, @post
  end

  def new
    @post = Post.new
    @post.user = current_user
    authorize! :new, @post
  end

  def edit
    authorize! :edit, @post
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    authorize! :create, @post

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
      @post.create_activity key: "post.create", owner: current_user, recipient: @post
    else
      render :new
    end
  end


  def update
    authorize! :update, @post
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
      @post.create_activity key: "post.update", owner: current_user, recipient: @post
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @post
    # @post.create_activity key: "post.destroy", owner: current_user, recipient: @post
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  def like
    authorize! :like, @post
    @post.liked_by current_user

    if request.xhr?
      redirect_back fallback_location: posts_path
    else
      redirect_back fallback_location: posts_path
    end
    @post.create_activity key: "post.like", owner: current_user, recipient: @post
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      # if use nested attributes:
      # params.require(:post).permit(:body, :key, comments_attributes: [:content])
      params.require(:post).permit(:body)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="row clearfix animated fadeIn pulse">

    <% if post.errors.any? %>
      <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
        <div class="panel">
          <div class="panel-default" id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
              <ul>
            <% post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>

    <%= render "layouts/notice-box" %>

    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
      <div class="panel panel-default">

        <div class="panel-heading" id="post-head">
          <div class="nav" >
            <div class="navbar-left" id="post-user-image">
              <%= image_tag post.user.image_url(:small), width: 50, height: 50, class: "img-circle" unless post.user.image_url.nil? %>&nbsp&nbsp
            </div>
            <div class="navbar-left" id="post-info">
              <%= link_to user_profile_path(post.user) do %>
                <p class="text-success btn" id="post-name"><%= post.user.name %></p>
              <% end %>
              <p class="text-default" id="post-time"><i class="fa fa-user-circle-o"> Editing</i></p>
            </div>
          </div>
        </div>

        <div class="panel-body">
          <div class="form-group">
            <div class="field" id="edit-body">
              <%= form.text_area :body, id: "edit-text", class: "form-control", required: true %>
            </div>
          </div>
        </div>

        <div class="panel-footer">
          <div class="btn btn-group">
            <div class="actions">
              <%= form.submit class: "btn btn-info" %>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
<% end %>

app/views/posts/_post.html.erb
  <div class="panel panel-default" id="post">
    <div class="panel-heading" id="post-head">
      <div class="nav navbar">
        <div class="navbar-left" id="post-user-image">
          <%= image_tag post.user.image_url(:small), width: 50, height: 50, class: "img-circle" unless post.user.image_url.nil? %>&nbsp&nbsp
        </div>
        <div class="navbar-left" id="post-info">
          <%= link_to user_profile_path(post.user) do %>
            <p class="text-success btn" id="post-name"><%= post.user.name %></p>
          <% end %>
          <% if post.public? %>
            <p class="text-default" id="post-time"><i class="fa fa-globe"> Published at <%= post.created_at %></i></p>
          <% else %>
            <p class="text-default" id="post-time"><i class="fa fa-user-circle-o"> Published at <%= post.created_at %></i></p>
          <% end %>
        </div>
        <% if post.user == current_user %>
          <div class="navbar-right" id="post-options">
            <div class="btn-group">
              <button type="button" class="btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expaned="false" id="post-option-open">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" id="post-option-menu">
                <li><%= link_to 'Modify', edit_post_path(post) %></li>
                <li><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="panel-body">
      <p id="post-body"><%= post.body %></p>
    </div>
    <% if user_signed_in? %>
      <div class="panel-footer">
        <div class="btn-group">
          <button type="button" class="btn btn-info">
            <%= link_to 'Like', like_post_path(post), method: :patch, remote: true %>
          </button>
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expaned="false">
            Comment
          </button>
          <ul class="dropdown-menu" id="comment-menu">

              <div class="nav navbar" id="comment-add">
                <div class="navbar-header" id="comment-user">
                  <div class="navbar-brand">
                    <%= image_tag current_user.image_url(:thumb), width: 20, height: 20, class: "img-circle" unless current_user.image_url.nil? %>
                  </div>
                </div>

                <%= form_with url: post_comments_path(post), method: :post, class: "navbar-form navbar-left" do |f| %>
                  <div class="form-group">
                    <%= f.text_field :content, placeholder: "Add Comment", class: "form-control", required: true, autocomplete: "off", id: "comment-field" %>
                  </div>
                  <%= f.submit "Enter", class: "btn btn-default" %>
                <% end %>

              </div>
          </ul>
        </div>
      </div>
    <% end %>
    <div class="panel-heading" id="reaction-options">
      <div class="heart">
        <i class="fa fa-heart"></i>
        <%= post.cached_votes_total %>
      </div>
    </div>
    <div class="panel-body" >
      <% @comments = post.comments.includes(:user) %>
      <%= render @comments || "comments/comment" %>
    </div>
  </div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/front.html.erb
<div class="row clearfix">
  <%= render "layouts/notice-box" %>

  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 animated fadeIn" id="posts-all">
    <% if @posts.present? %>
      <%= render @posts %>
    <% else %>
      <div class="jumbotron">
        <h1>Sorry, no public post for now!</h1>
        <h2>Maybe you should sign up?</h2>
        <br>
        <span class="label label-warning"><%= link_to "Sign up", new_user_registration_path %></span>
      </div>
    <% end %>
  </div>

</div>

app/views/posts/index.html.erb
<div class="row clearfix">
  <%= render "layouts/notice-box" %>

  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 animated fadeIn" id="posts-all">
    <% if @posts.present? %>
      <%= render @posts %>
    <% else %>
      <div class="jumbotron">
        <h1>Sorry, no results found!</h1>
        <h2>Maybe try other keywords?</h2>
        <br>
        <span class="label label-warning"><%= link_to "Back", posts_path %></span>
      </div>
    <% end %>
  </div>

</div>

<div class="row" id="page-bar">
  <div class="col-md-4 col-md-offset-4">
    <%# will_paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="row clearfix">
  <%= render "layouts/notice-box" %>
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
    <%= render @post || "post" %>
  </div>
</div>