config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'

  devise_for :users, skip: "registrations"
  devise_scope :user do
    get "users/sign_up", to: "devise/registrations#new", as: "new_user_registration"
    post "users/sign_up", to: "devise/registrations#create", as: "user_registration"
    get "users/account", to: "devise/registrations#edit", as: "edit_user_registration"
    put "users/update", to: "devise/registrations#update", as: "update_user_registration"
    delete "users/clean", to: "devise/registrations#destroy", as: "clean_up"

  end

  get "admin", to: "users#index", as: "admin"
  get "users/:id", to: "users#show", as: "user_profile"
  patch "users/:id/subscribe", to: "users#follow"
  patch "users/:id/unsubscribe", to: "users#unfollow"
  patch "users/:id/ban", to: "users#ban"
  patch "users/:id/warn", to: "users#warn"

  get "activities", to: "activities#log"
  get "admin/activities", to: "activities#index"
  get "admin/activities/:id", to: "activities#show"

  resources :notifications, only: [:log, :index, :show, :create, :destroy]

  resources :posts do
    member do
      patch 'like', to: "posts#like"
    end
    resources :comments
  end

  resources :messages

  resources :friendships, only: [:log, :index, :show, :create, :destroy]

  root "posts#front"

  mount ActionCable.server => "/cable"
end

app/views/layouts/_activity.html.erb
<% if activity.owner.present? && activity.recipient.present? %>

  <% translates = {"post.create" => "recently posts this", "post.update" => "updated this post", "post.destroy" => "deleted this post", "post.like" => "liked this post", \
                  "comment.create" => "commented on a post", "comment.update" => "modified a comment on a post", "comment.destroy" => "deleted a comment on a post", \
                  "friendship.create" => "makes firend with", "friendship.destroy" => "unfriended", \
                  "user.follow" => "subscribes to", "user.unfollow" => "cancelled following", "user.ban" => "banned", "user.warn" => "warns"} %>

    <% if activity.recipient_type == "Post" %>
      <div class="panel-heading" id="activity-head">
        <h2>
          <%= link_to user_profile_path(activity.owner.id) do %>
            <%= activity.owner.name %>
          <% end %>
          <%= "#{translates[activity.key]}" %>
        </h2>
        <%= activity.created_at %>
      </div>
      <div class="panel-body">
        <% post = Post.find(activity.recipient_id) %>
        <%= render post || "posts/post" %>
      </div>

    <% elsif activity.recipient_type == "User" %>
      <div class="panel-heading" id="activity-head">
        <h2>
          <%= link_to user_profile_path(activity.owner.id) do %>
            <%= activity.owner.name %>
          <% end %>
          <%= "#{translates[activity.key]}" %>
          <%= link_to user_profile_path(activity.recipient.id) do %>
            <%= activity.recipient.name %>
          <% end %>
        </h2>


        <%= activity.created_at %>
      </div>

    <% else %>
      <div class="panel-heading" id="activity-head">
        <h1>Unknown Activity</h1>
      </div>
    <% end %>

<% end %>

app/views/layouts/_header.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<%= action_cable_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">

app/views/layouts/_messages.html.erb
<div class="panel" id="message-board">
  <div class="panel-body" id="messages">
  </div>
  <div class="panel-footer" id="message-write">
    <%= form_with model: current_user.messages.new do |f|%>
      <%= f.text_field :content, placeholder: "Enter your message", id: "messageInput", class: "form-control", required: true, autocomplete: "off" %>
      <%= f.submit "send", class: "btn btn-primary", style: "display: none" %>
    <% end %>
  </div>
</div>

app/views/layouts/_notice-box.html.erb
<% if notice.present? %>
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
    <div class="panel panel-default animated fadeIn" id="notice-box">
      <p id="notice"><%= notice %></p>
    </div>
  </div>
<% end %>

app/views/layouts/_zuckerbar.html.erb
<div class="navbar-left">
  <% if user_signed_in? %>
    <a href="/posts" class="navbar-brand animated rubberBand" id="Zuckerbrand"><strong>Markbook</strong></a>
  <% else %>
    <a href="/" class="navbar-brand animated fadeIn" id="Zuckerbrand"><strong>Markbook</strong></a>
  <% end %>
</div>
<div id="Zucker-search">
  <%= form_with url: posts_path, method: :get, class: "navbar-form navbar-left", local: true do |f| %>
    <div class="form-group">
      <%= f.text_field :key, placeholder: "Any Keywords", class: "form-control", required: true %>
    </div>
    <%= f.submit "Search", class: "btn btn-default" %>
  <% end %>
</div>
<div class="navbar navbar-nav navbar-right" id="Zucker-menu">
  <div class="btn btn-group">
    <% if user_signed_in? %>
      <% if current_user.banned? %>
        <span class="label label-danger btn" >You've been banned by Zucker</span>
      <% else %>
        <%= link_to new_post_path, class: "btn" do %>
          <i class="fa fa-pencil"> Post</i>
        <% end %>
      <% end %>
      <%= link_to edit_user_registration_path, class: "btn" do%>
        <i class="fa fa-cog"> Account</i>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "Are you sure to leave?" }, class: "btn" do%>
        <i class="fa fa-sign-out"> Sign Out</i>
      <% end %>
    <% else %>
      <%= link_to user_registration_path, class: "btn" do %>
        <span class="fa fa-user-plus"> Sign Up</span>
      <% end %>
      <%= link_to new_user_session_path, class: "btn" do %>
        <span class="fa fa-sign-in"> Sign In</span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Markbook</title>
    <%= render "layouts/header" %>
  </head>

  <body>
    <div class="navbar navbar-inverse" id="Zuckerbar">
      <div class="container">
        <%= render "layouts/zuckerbar" %>
      </div>
    </div>

    <div class="container" id="main">
      <%= yield %>
    </div>

    <% if user_signed_in? %>
      <div class="navbar navbar-nav navbar-inverse navbar-fixed-bottom">
        <div class="container">
          <center>
            <button id="message-open" onclick="openMessageBoard()">
              <span class="glyphicon glyphicon-chevron-up"></span>
            </button>
            <button id="message-close" onclick="closeMessageBoard()">
              <span class="glyphicon glyphicon-chevron-down"></span>
            </button>
          </center>
          <center>
            <%= render "layouts/messages" %>
          </center>
        </div>
      </div>

      <script>
        function openMessageBoard(){
          document.getElementById("message-open").style.display="none"
          document.getElementById("message-close").style.display="block"
          document.getElementById("message-board").style.display="block"
          document.getElementsByTagName("body")[0].style.padding=" 0 0 250px 0"
        }
        function closeMessageBoard(){
          document.getElementById("message-open").style.display="block"
          document.getElementById("message-close").style.display="none"
          document.getElementById("message-board").style.display="none"
          document.getElementsByTagName("body")[0].style.padding=" 0 0 50px 0"
        }
      </script>
    <% end %>

  </body>
</html>